profile view
projekt-fitnessapp/frontend pull request #16
Opened 2022-09-27 15:14 UTC by RebekkaMiguez

ProfileView und MyDataView stehen so weit, werde aber noch das Ganze weiter nach bessern. Muss mir eine bessere Lösung finden für die DropDownButtons. Die LoginView ist zwar da, aber ich habe da noch kein Google SSO implementiert. Ich habe mich jetzt komplett auf die Mock Ups orientiert, falls ihr noch Vorschläge habt wäre das super.

2022-09-28 06:13 UTC, binhdich commented
hab noch nicht 100% drübergeschaut aber wenn du deinen code ein bissl aufräumen magst, würd ich dir empfehlen das TextfieldWidget und die Sizeboxes in edit_profile_view als widget zusammenzufassen und das label als parameter zu übergeben. dann einfach eine liste an strings der unterschiedlichen labels erstellen und über listview.builder für jeden string dieser liste das entsprechende widget erstellen lassen. gleiches für buildDataRow und SizedBox bei my_profile_view. Bei question_widget kannste auch einmal buildQuestion + buildTextField und einmal buildQuestion + buildDropdown je zusammenfassen. aber absolut kein muss du sparst dir dadurch nicht viel mehr code. sonst seh ich auf den ersten blick noch nichts weiteres. würd aber empfehlen dass noch jmd anderes drüberschaut mir entgeht vieles.

2022-10-05 07:36 UTC, MatthiasBiermanns requested changes

2022-10-05 07:36 UTC, MatthiasBiermanns commented on tromega/lib/views/account/Example/user.dart
> +}
Bitte hier einen Konstruktor anlegen und nicht eine const von User:
User(this.imgPath, this.name ...usw)

2022-10-05 07:36 UTC, MatthiasBiermanns commented on tromega/lib/views/account/Example/user.dart
> +  final String age;
Bitte auch Typen anpassen. 'age' ist sicher kein String

2022-10-05 07:36 UTC, MatthiasBiermanns commented on tromega/lib/views/account/questions_widget.dart
> +}
Unbedint nur eine Klasse pro Datei

2022-10-05 07:36 UTC, MatthiasBiermanns commented on tromega/lib/views/account/edit_profile_view.dart
> +              onClicked: () async {},
Warum ist die function hier async?

2022-10-05 07:36 UTC, MatthiasBiermanns commented on tromega/lib/views/account/my_profile_view.dart
> +      bottomNavigationBar: const BottomMenu(index: 1),
Index hier wieder auf 4 setzen, denke mal ein copy/paste fehler, oder?

2022-10-05 07:36 UTC, MatthiasBiermanns commented on tromega/lib/views/account/questions_widget.dart
> +      );
So widgets kannst du auch gerne in eigene Dateien als custom widgets auslagern... muss jetzt aber noch nicht unbedingt

2022-10-05 07:36 UTC, MatthiasBiermanns commented on tromega/lib/views/account/questions_widget.dart
> +              MaterialPageRoute(builder: (context) => const ProfileView()),
hier gerne Navigator.push() durch .pushNamed() wechseln und die routes aus der main.dart verwenden

2022-10-05 07:37 UTC, MatthiasBiermanns commented
Sorry, dass die Code-Referenzen nicht so supi sind, guck am besten einfach in den 4 Zeilen und darüber. Darauf sollte sich der Comment dann beziehen

2022-10-11 12:20 UTC, lumaghg commented
@RebekkaMiguez bitte einmal irgendwas pushen, damit der neue Build Health Check getriggert wird, sonst wird das mergen automatisch geblockt

2022-10-11 12:43 UTC, steffenhls commented
![image](https://user-images.githubusercontent.com/73340772/195093718-6b92bd95-6078-4096-a6e5-98991a0c3b32.png)
Bitte drum kümmern, sonst wird der check-build-health auch nicht durchgehen

2022-10-12 08:17 UTC, steffenhls commented
![image](https://user-images.githubusercontent.com/73340772/195289016-440f4c68-69b7-47a6-9cba-e4e5618eab64.png)

2022-10-12 09:13 UTC, lumaghg commented
@steffenhls ich kümmere mich um den build health check

2022-10-12 09:17 UTC, MatthiasBiermanns commented on tromega/lib/widgets/account/dropdown_widget.dart
> +              }),
Value lässt sich hier nicht ändern, weil du den Value festsetzt und bei onChanged nicht änderst. Solltest hier bitte folgendes einbauen:

Vor die Build-Methode
late String value;

@override
initState() {
  value = widget.dropDownValue
}

onChanged Function ersetzen durch:
(changedValue) {
  setState(() {
    value = changedValue
  });
}

Sollte so funktionieren, falls nicht, hoffe ich die Idee ist klar

2022-10-12 09:18 UTC, MatthiasBiermanns approved these changes

2022-10-12 09:18 UTC, lumaghg commented
@steffenhls kannst du mal den base branch auf main ändern und dann wieder zurück zu dev

2022-10-12 09:19 UTC, lumaghg commented
> @steffenhls kannst du mal den base branch auf main ändern und dann wieder zurück zu dev

Stackoverflow sagt der PR ist stuck und muss irgendwie refreshed werden

2022-10-12 10:56 UTC, merged