Stats screen
projekt-fitnessapp/frontend pull request #57
Opened 2023-03-05 14:41 UTC by MaikKBRNK

Ich habe auf der Home-View hinzugefügt, dass, wenn kein Training ausgewählt ist, auch der Button nicht klickbar ist und kein Training angezeigt wird. Auch sieht man da jetzt das aktuelle nächste Training. Ansonsten habe ich mal was für die Statistikseite gebaut. Da werde ich aber noch an der Darstellung (sollte Scrollable sein, sowie fabrlich vielleicht etwas besser aussehen) arbeiten. Aktuell warte ich hier aber noch auf die Backendanbindung. Ich wollte es aber schon mal mergen, da wir ja zu mehr Merges gebeten wurden.

2023-03-05 20:41 UTC, steffenhls requested changes
Sieht stark aus, finde den Abstand zwischen den Graphen noch bissl zu groß und hab dir paar weitere Kommentare hinterlegt. Danke für dein Engagement 👍

2023-03-05 20:41 UTC, steffenhls commented on tromega/lib/views/home_view.dart
> +                              primary: nextTraining != 'Kein Plan ausgewählt'
Was passiert, wenn mein Trainingstag _Kein Plan ausgewählt_ heißt? :D denke ist ein lustiges easter egg

2023-03-05 20:41 UTC, steffenhls commented on tromega/lib/views/statistics_view.dart
> +        ),
bitte unsere appbar nehmen

2023-03-05 20:41 UTC, steffenhls commented on tromega/lib/views/home_view.dart
> +      print(getNextTraining);
print bitte rausnehmen

2023-03-05 20:41 UTC, steffenhls commented on tromega/lib/views/home_view.dart
> +    String getNextTraining = await homeHttpHelper.getNextTrainingDayName();
variablen als getter zu bennenen ist verwirrend

2023-03-05 20:41 UTC, steffenhls commented on tromega/lib/views/statistics_view.dart
> +                          ]),
Bitte in weiteres Widget extrahieren und durch die Liste der Ergebnisse dann erstellen

2023-03-08 11:29 UTC, MaikKBRNK commented on tromega/lib/views/home_view.dart
> +                              primary: nextTraining != 'Kein Plan ausgewählt'
Das fixe ich beim nächsten Mal👍

2023-03-08 12:02 UTC, MatthiasBiermanns approved these changes
Klasse bitte noch auslagern, ich approve aber schonmal!
Rest sieht gut aus. Vielen Dank für die Arbeit

2023-03-08 12:02 UTC, MatthiasBiermanns commented on tromega/lib/data/stats_pair.dart
> +class OneGraph {
Klasse bitte noch in eine eigene File, auch wenn sie nur so klein ist. Hilft anderen einfach den Code zu finden

2023-03-08 12:12 UTC, steffenhls approved these changes

2023-03-08 12:12 UTC, merged